CREATE TABLE listwish_lists (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    list_title TEXT NOT NULL,
    list_description TEXT,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);